version: '3'
services:
  db:
    image: postgres:11.2
    ports:
      - 5434:5432
    volumes:
      - "../postgresql/data:/var/lib/postgresql/data"
  web:
    build: .
    image: "happy_shop"
    command: "bundle exec rails server -p 8000 -b 0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - db
