version: '3'
services:
  db:
    image: postgres:11.2
    ports:
      - 5432:5432
    volumes:
      - "../postgresql/data:/var/lib/postgresql/data"
  web:
    build: .
    image: "happy_shop"
    command: "bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - db
  migrations:
    image: "happy_shop"
    command: "rails db:migrate"
    depends_on:
      - db
      - web
